//! Byte tables for Manic Miner, transcribed from the published disassembly.
//!
//! Every table here is data from the 1983 ZX Spectrum release: cavern layouts,
//! tile and sprite bitmaps, guardian definitions and the two tunes. The modules
//! are generated by `tools/gen_data.py` and contain no logic.
//!
//! Manic Miner is Copyright (c) 1983 Matthew Smith / Bug-Byte Ltd.

pub mod caverns;
pub mod guardians;
pub mod music;
pub mod sprites;
pub mod tiles;
pub mod title;

/// Number of caverns in the game.
pub const CAVERN_COUNT: usize = 20;

/// The cavern index of The Final Barrier, which has its own ending sequence.
pub const FINAL_BARRIER: usize = 19;

/// The eight tile kinds a cavern cell can hold, in the order the loader reads them.
///
/// The `EXTRA` tile does duty as several things depending on the cavern: a floor
/// in the forest caverns, spider silk in The Menagerie, and a switch in the two
/// Kong Beast caverns.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub enum TileKind {
    Background,
    Floor,
    Crumbling,
    Wall,
    Conveyor,
    Nasty1,
    Nasty2,
    Extra,
}

impl TileKind {
    /// Every tile kind, in loader order.
    pub const ALL: [TileKind; 8] = [
        TileKind::Background,
        TileKind::Floor,
        TileKind::Crumbling,
        TileKind::Wall,
        TileKind::Conveyor,
        TileKind::Nasty1,
        TileKind::Nasty2,
        TileKind::Extra,
    ];

    /// The nine bytes defining this tile in `cavern`: attribute byte then eight sprite rows.
    pub fn data(self, cavern: usize) -> &'static [u8; 9] {
        match self {
            TileKind::Background => &tiles::TILE_BACKGROUND[cavern],
            TileKind::Floor => &tiles::TILE_FLOOR[cavern],
            TileKind::Crumbling => &tiles::TILE_CRUMBLING[cavern],
            TileKind::Wall => &tiles::TILE_WALL[cavern],
            TileKind::Conveyor => &tiles::TILE_CONVEYOR[cavern],
            TileKind::Nasty1 => &tiles::TILE_NASTY1[cavern],
            TileKind::Nasty2 => &tiles::TILE_NASTY2[cavern],
            TileKind::Extra => &tiles::TILE_EXTRA[cavern],
        }
    }
}
