// Generated by tools/gen_jsw_data.py from the published Jet Set Willy disassembly.
// Jet Set Willy is Copyright (c) 1984 Software Projects Ltd.
// Do not edit by hand.

/// Moonlight Sonata, played over the title screen. Each byte is a pitch delay, and 255 ends it.
pub const THEME: [u8; 100] = [
        81, 60, 51, 81, 60, 51, 81, 60, 51, 81, 60, 51, 81, 60, 51, 81, 60, 51, 81, 60, 51, 81,
        60, 51, 76, 60, 51, 76, 60, 51, 76, 57, 45, 76, 57, 45, 81, 64, 45, 81, 60, 51, 81, 60,
        54, 91, 64, 54, 102, 81, 60, 81, 60, 51, 81, 60, 51, 40, 60, 40, 40, 54, 45, 81, 54, 45,
        81, 54, 45, 40, 54, 40, 40, 60, 51, 81, 60, 51, 38, 60, 45, 76, 60, 45, 40, 64, 51, 81,
        64, 51, 45, 64, 54, 32, 64, 54, 61, 121, 61, 255
    ];

/// If I Were a Rich Man, played while the game runs. Each byte is a pitch delay, and the tune repeats for ever.
pub const GAME: [u8; 64] = [
        86, 96, 86, 96, 102, 102, 128, 128, 128, 128, 102, 96, 86, 96, 86, 96, 102, 96, 86, 76,
        72, 76, 72, 76, 86, 86, 86, 86, 86, 86, 86, 86, 64, 64, 64, 64, 68, 68, 76, 76, 86, 96,
        102, 96, 86, 86, 102, 102, 81, 86, 96, 86, 81, 81, 96, 96, 64, 64, 64, 64, 64, 64, 64,
        64
    ];

