#!/usr/bin/env python3
"""Convert the reference C arrays into Rust `pub const` tables for mm-data."""
import re, sys, os, textwrap

SRC = os.path.join(os.path.dirname(__file__), "ref-cpp", "src")
OUT = sys.argv[1]

def load(path):
    with open(os.path.join(SRC, path)) as f:
        txt = f.read()
    txt = re.sub(r"/\*.*?\*/", "", txt, flags=re.S)
    txt = re.sub(r"//[^\n]*", "", txt)
    return txt

def find_array(txt, name):
    """Return the body text between the outermost braces of `name`'s initialiser."""
    m = re.search(r"\b" + re.escape(name) + r"\s*(\[[^=]*?)=\s*\{", txt)
    if not m:
        raise SystemExit("array not found: " + name)
    i = m.end() - 1
    depth = 0
    for j in range(i, len(txt)):
        if txt[j] == "{":
            depth += 1
        elif txt[j] == "}":
            depth -= 1
            if depth == 0:
                return txt[i + 1 : j]
    raise SystemExit("unterminated: " + name)

def nums(body):
    return [int(x) for x in re.findall(r"-?\d+", body)]

def parse_nested(body):
    """Parse a C initialiser body into nested lists, preserving brace structure."""
    stack = [[]]
    for tok in re.finditer(r"\{|\}|-?\d+", body):
        t = tok.group(0)
        if t == "{":
            stack.append([])
        elif t == "}":
            done = stack.pop()
            stack[-1].append(done)
        else:
            stack[-1].append(int(t))
    return stack[0]

def reshape(value, dims):
    """Conform a parsed initialiser to `dims`, zero-filling omitted trailing entries.

    C allows partial initialisers, so a row written as `{1, 2}` in a `[5]` slot
    means `{1, 2, 0, 0, 0}`. Braces around inner rows are optional too, in which
    case the values arrive flattened and have to be chunked.
    """
    if len(dims) == 1:
        flat = [x for x in value if isinstance(x, int)]
        assert len(flat) <= dims[0], (len(flat), dims)
        return flat + [0] * (dims[0] - len(flat))
    rows = [x for x in value if isinstance(x, list)]
    if not rows:
        step = 1
        for d in dims[1:]:
            step *= d
        flat = [x for x in value if isinstance(x, int)]
        flat += [0] * (dims[0] * step - len(flat))
        rows = [flat[i * step : (i + 1) * step] for i in range(dims[0])]
    assert len(rows) <= dims[0], (len(rows), dims)
    out = [reshape(r, dims[1:]) for r in rows]
    while len(out) < dims[0]:
        out.append(reshape([], dims[1:]))
    return out

def fmt(v, indent=0):
    pad = "    " * indent
    if not isinstance(v, list):
        return str(v)
    if not isinstance(v[0], list):
        line = ", ".join(str(x) for x in v)
        if len(line) <= 92:
            return "[" + line + "]"
        wrapped = textwrap.wrap(line, width=92)
        inner = ("\n" + pad + "    ").join(wrapped)
        return "[\n" + pad + "    " + inner + "\n" + pad + "]"
    parts = [fmt(x, indent + 1) for x in v]
    return "[\n" + "".join(pad + "    " + p + ",\n" for p in parts) + pad + "]"

def emit(f, name, ty, dims, flat, doc=None):
    data = reshape(flat, dims)
    rust_ty = ty
    for d in reversed(dims):
        rust_ty = f"[{rust_ty}; {d}]"
    if doc:
        for line in doc.strip().splitlines():
            f.write(f"/// {line.strip()}\n")
    f.write(f"pub const {name}: {rust_ty} = {fmt(data)};\n\n")

caverns = load("data/caverns.cpp")
tiles = load("data/tiles.cpp")
guards = load("data/guardian_sprites.cpp")
music = load("data/music.cpp")
title = load("data/title_screen.cpp")
willy = load("data/willy_sprites.cpp")

os.makedirs(OUT, exist_ok=True)
HEAD = """\
// Generated by tools/gen_data.py from the published Manic Miner disassembly.
// Manic Miner is Copyright (c) 1983 Matthew Smith / Bug-Byte Ltd.
// Do not edit by hand.

"""

# ---- caverns.rs -------------------------------------------------------------
with open(os.path.join(OUT, "caverns.rs"), "w") as f:
    f.write(HEAD)
    names = re.findall(r'"((?:[^"\\]|\\.)*)"', find_array(caverns, "Data_cavernNames"))
    assert len(names) == 20, len(names)
    f.write("/// The name shown on the status bar, exactly 32 characters wide.\n")
    f.write("pub const CAVERN_NAMES: [&str; 20] = [\n")
    for n in names:
        f.write(f'    "{n}",\n')
    f.write("];\n\n")

    specs = [
        ("WILLY_START_PIXEL_Y", "u8", [20], "Data_pixelY", "Willy's initial pixel y-coordinate in each cavern."),
        ("WILLY_START_FRAME", "u8", [20], "Data_frames", "Willy's initial animation frame."),
        ("WILLY_START_DIRECTION", "u8", [20], "Data_dmFlags", "Willy's initial direction and movement flags."),
        ("WILLY_START_AIRBORNE", "u8", [20], "Data_airborneStatues", "Willy's initial airborne status."),
        ("WILLY_START_LOCATION", "u16", [20], "Data_locations", "Willy's start cell as an attribute-buffer address."),
        ("WILLY_START_JUMP", "u8", [20], "Data_jumpingStatuses", "Willy's initial jumping counter."),
        ("CONVEYOR_PARAMS", "u16", [20, 3], "Data_conveyorBeltsParams", "Per cavern: direction, screen-buffer address, length."),
        ("BORDER_COLOURS", "u8", [20], "Data_borderColours", "Screen border colour for each cavern."),
        ("ITEM_ATTRS", "u8", [20], "Data_itemAttrs", "Base attribute byte of the collectable items."),
        ("ITEMS", "u16", [20, 5, 5], "Data_itemsData", "Five item slots per cavern: attribute, address, screen MSB, unused."),
        ("PORTAL_ATTRS", "u8", [20], "Data_portalAttributes", "Attribute byte of the portal."),
        ("PORTAL_GRAPHICS", "u8", [20, 32], "Data_portalGraphics", "16x16 portal sprite, two bytes per row."),
        ("PORTAL_ATTR_LOCATIONS", "u16", [20], "Data_portalAttributeLocations", "Portal position as an attribute-buffer address."),
        ("PORTAL_SCREEN_LOCATIONS", "u16", [20], "Data_portalScreenLocations", "Portal position as a screen-buffer address."),
        ("ITEM_GRAPHICS", "u8", [20, 8], "Data_itemGraphics", "8x8 sprite used for every item in the cavern."),
        ("AIR_SUPPLIES", "u8", [20], "Data_airSupplies", "Initial air supply."),
        ("CLOCK_VALUES", "u8", [20], "Data_clockValues", "Initial game clock value."),
        ("LAYOUTS", "u8", [20, 512], "Data_cavernLayouts", "32x16 tile map, one attribute byte per cell."),
        ("SCREEN_BUFFER_ADDRS", "u16", [128], "SBUFADDRS", "Screen-buffer address of the start of each pixel row."),
    ]
    for name, ty, dims, cname, doc in specs:
        emit(f, name, ty, dims, parse_nested(find_array(caverns, cname)), doc)

# ---- tiles.rs ---------------------------------------------------------------
with open(os.path.join(OUT, "tiles.rs"), "w") as f:
    f.write(HEAD)
    emit(f, "SWORDFISH", "u8", [32], parse_nested(find_array(tiles, "SWORDFISH")),
         "Swordfish shown on The Final Barrier when the game is completed.")
    emit(f, "PLINTH", "u8", [32], parse_nested(find_array(tiles, "PLINTH")), "Plinth on the Game Over screen.")
    emit(f, "BOOT", "u8", [32], parse_nested(find_array(tiles, "BOOT")), "The descending boot.")
    emit(f, "EUGENE", "u8", [32], parse_nested(find_array(tiles, "EUGENEG")), "Eugene, the guardian of Eugene's Lair.")
    kinds = [
        ("BACKGROUND", "Data_tileBackgrounds"),
        ("FLOOR", "Data_tileFloors"),
        ("CRUMBLING", "Data_tileCrumblingFloors"),
        ("WALL", "Data_tileWalls"),
        ("CONVEYOR", "Data_tileConveyorBelts"),
        ("NASTY1", "Data_tileNasties1"),
        ("NASTY2", "Data_tileNasties2"),
        ("EXTRA", "Data_tileExtras"),
    ]
    for name, cname in kinds:
        emit(f, "TILE_" + name, "u8", [20, 9], parse_nested(find_array(tiles, cname)),
             f"Per cavern {name.lower()} tile: attribute byte followed by eight sprite rows.")

# ---- guardians.rs -----------------------------------------------------------
with open(os.path.join(OUT, "guardians.rs"), "w") as f:
    f.write(HEAD)
    emit(f, "HORIZONTAL", "u16", [20, 4, 6], parse_nested(find_array(guards, "Data_horizontalGuardianLocations")),
         "Four horizontal guardian slots per cavern: attribute, address, frame, direction, min, max.")
    emit(f, "VERTICAL", "u8", [20, 4, 7], parse_nested(find_array(guards, "Data_verticalGuardianLocations")),
         "Four vertical guardian slots per cavern: attribute, frame, x, y, direction, min, max.")
    emit(f, "SPRITES", "u8", [20, 256], parse_nested(find_array(guards, "Data_guardianSprites")),
         "Eight 16x16 guardian frames per cavern, 32 bytes each.")

# ---- sprites.rs -------------------------------------------------------------
with open(os.path.join(OUT, "sprites.rs"), "w") as f:
    f.write(HEAD)
    emit(f, "WILLY", "u8", [256], parse_nested(find_array(willy, "WILLYDATA")),
         "Eight 16x16 Willy frames: four facing right, then four facing left.")
    # The ROM font is not Manic Miner's: it lives in crates/speccy/src/font.rs,
    # where every game can print with it, and is not regenerated from here.

# ---- music.rs ---------------------------------------------------------------
with open(os.path.join(OUT, "music.rs"), "w") as f:
    f.write(HEAD)
    emit(f, "THEME_TUNE", "u8", [95, 3], parse_nested(find_array(music, "THEMETUNE")),
         "The Blue Danube, played on the title screen: duration, then two pitch bytes.")
    emit(f, "GAME_TUNE", "u8", [64], parse_nested(find_array(music, "GAMETUNE")),
         "In the Hall of the Mountain King, played during a cavern: one pitch byte per note.")

# ---- title.rs ---------------------------------------------------------------
with open(os.path.join(OUT, "title.rs"), "w") as f:
    f.write(HEAD)
    f.write("/// Message that scrolls across the status area of the title screen.\n")
    f.write(
        'pub const INTRO_MESSAGE: &str = ".  .  .  .  .  .  .  .  .  .  . MANIC MINER . . '
        '(c) 1983 Bug-Byte Ltd. . . By Matthew Smith . . . '
        'Arrow keys = Left & Right . . Space = Jump . . '
        'P = Pause . . M = Tune On/Off . . Q = Quit . . . ";\n\n'
    )
    emit(f, "TITLE_SCREEN_PIXELS", "u8", [2048], parse_nested(find_array(title, "TITLESCR1")),
         "Top third of the title screen display file.")
    emit(f, "TITLE_SCREEN_ATTRS", "u8", [2048], parse_nested(find_array(title, "TITLESCR2")),
         "Attributes and piano graphic for the title screen.")
    emit(f, "LOWER_ATTRS", "u8", [512], parse_nested(find_array(title, "LOWERATTRS")),
         "Attributes for the lower two thirds of the title screen.")

print("written to", OUT)
