#!/usr/bin/env python3
"""Generate the jsw-data modules from SkoolKit's Jet Set Willy disassembly.

Not part of the build. Run it only when the tables need to change:

    uv tool install skoolkit          # provides skool2bin.py
    git clone --depth 1 \\
      https://gitlab.com/z80-source-code-software/other-systems/jet-set-willy-disassembly---zx-spectrum \\
      /tmp/jsw
    python3 tools/gen_jsw_data.py crates/jsw-data/src

SkoolKit assembles the .skool file back into the 64K image the game ran in, and
everything below is read out of that by absolute address. So what lands in
jsw-data is the game's own bytes rather than anyone's transcription of them, and
it can be checked against the disassembly line by line.
"""

import os
import re
import subprocess
import sys
import tempfile

SKOOL = os.environ.get("JSW_SKOOL", "/tmp/jsw/sources/jsw.skool")
OUT = sys.argv[1] if len(sys.argv) > 1 else "crates/jsw-data/src"

# Where the game keeps things. Confirmed against the disassembly.
ROOMS = 0xC000
ROOM_COUNT = 64
ROOM_SIZE = 0x100

ENTITY_DEFS = 0xA000
ENTITY_DEF_COUNT = 128
ENTITY_DEF_SIZE = 8

ITEM_TABLE = 0xA400
FIRST_ITEM = 173

WILLY_SPRITES = 0x9D00
MARIA_SPRITE = 0x9C80
GUARDIAN_GRAPHICS = 0xAB00
TOILET_GRAPHICS = 0xA600
ROPE_TABLE = 0x8300

HEAD = """\
// Generated by tools/gen_jsw_data.py from the published Jet Set Willy disassembly.
// Jet Set Willy is Copyright (c) 1984 Software Projects Ltd.
// Do not edit by hand.

"""


# ---- reading the disassembly ------------------------------------------------

def load_image(path):
    """Assemble the .skool file into a 64K image.

    SkoolKit's own assembler does this. Walking the DEFB lines by hand almost
    works, but a few hundred bytes of rooms 47 and 61 to 63 are disassembled as
    instructions rather than data — those rooms hold code and unused junk in the
    real game — and reassembling those needs a Z80 assembler.
    """
    with tempfile.TemporaryDirectory() as work:
        binary = os.path.join(work, "jsw.bin")
        result = subprocess.run(
            ["skool2bin.py", "--data", path, binary],
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            sys.exit(f"skool2bin.py failed:\n{result.stderr.strip()}")

        # It reports the address range it wrote; the file itself is just bytes.
        match = re.search(r"start=(\d+)", result.stderr + result.stdout)
        if not match:
            sys.exit(f"could not read skool2bin's output:\n{result.stderr.strip()}")
        base = int(match.group(1))

        with open(binary, "rb") as handle:
            data = handle.read()

    memory = bytearray(65536)
    memory[base:base + len(data)] = data
    return memory


# ---- writing Rust -----------------------------------------------------------

def fmt(data):
    """Format a nested list as a Rust array literal, wrapped at 92 columns."""
    if isinstance(data[0], list):
        return "[\n" + ",\n".join("    " + fmt_row(row) for row in data) + "\n]"
    return fmt_row(data)


def fmt_row(row):
    if isinstance(row[0], list):
        return "[" + ", ".join(fmt_row(inner) for inner in row) + "]"
    body = ", ".join(str(v) for v in row)
    if len(body) <= 88:
        return "[" + body + "]"
    lines, current = [], "    "
    for value_text in (str(v) + "," for v in row):
        if len(current) + len(value_text) > 92:
            lines.append(current.rstrip())
            current = "    "
        current += value_text + " "
    lines.append(current.rstrip().rstrip(","))
    return "[\n" + "\n".join("    " + line for line in lines) + "\n    ]"


def emit(handle, name, rust_ty, dims, data, doc):
    ty = rust_ty
    for dim in reversed(dims):
        ty = f"[{ty}; {dim}]"
    handle.write(f"/// {doc}\n")
    handle.write(f"pub const {name}: {ty} = {fmt(data)};\n\n")


# ---- extraction -------------------------------------------------------------

def main():
    if not os.path.exists(SKOOL):
        sys.exit(
            f"cannot find {SKOOL}\n"
            "clone the disassembly first, or set JSW_SKOOL to its jsw.skool"
        )

    memory = load_image(SKOOL)
    check(memory)

    os.makedirs(OUT, exist_ok=True)
    rooms = [
        memory[ROOMS + n * ROOM_SIZE: ROOMS + (n + 1) * ROOM_SIZE]
        for n in range(ROOM_COUNT)
    ]

    with open(os.path.join(OUT, "rooms.rs"), "w") as f:
        f.write(HEAD)
        emit(f, "ROOMS", "u8", [ROOM_COUNT, ROOM_SIZE], [list(r) for r in rooms],
             "The 64 room definitions, 256 bytes each, exactly as they sit at 49152.")
        emit(f, "ROOM_NAMES", "u8", [ROOM_COUNT, 32],
             [list(r[0x80:0xA0]) for r in rooms],
             "Room names, 32 bytes each, printed through the ROM font. Rooms 61 to "
             "63 hold code rather than a room, so their names are not text.")

    with open(os.path.join(OUT, "entities.rs"), "w") as f:
        f.write(HEAD)
        defs = [
            list(memory[ENTITY_DEFS + n * ENTITY_DEF_SIZE:
                        ENTITY_DEFS + (n + 1) * ENTITY_DEF_SIZE])
            for n in range(ENTITY_DEF_COUNT)
        ]
        emit(f, "ENTITY_DEFS", "u8", [ENTITY_DEF_COUNT, ENTITY_DEF_SIZE], defs,
             "Entity definitions: ropes, arrows and guardians, eight bytes each.")
        emit(f, "ROPE_TABLE", "u8", [256], list(memory[ROPE_TABLE:ROPE_TABLE + 256]),
             "How far to rotate a rope's sprite at each point along its swing.")

    with open(os.path.join(OUT, "items.rs"), "w") as f:
        f.write(HEAD)
        f.write("/// The lowest numbered item. Items below this are not in the game.\n")
        f.write(f"pub const FIRST_ITEM: usize = {FIRST_ITEM};\n\n")
        emit(f, "ITEM_TABLE", "u8", [2, 256],
             [list(memory[ITEM_TABLE:ITEM_TABLE + 256]),
              list(memory[ITEM_TABLE + 256:ITEM_TABLE + 512])],
             "The two halves of the item table: room and position of each of the 83 items.")

    with open(os.path.join(OUT, "sprites.rs"), "w") as f:
        f.write(HEAD)
        emit(f, "WILLY", "u8", [256], list(memory[WILLY_SPRITES:WILLY_SPRITES + 256]),
             "Eight 16x16 Willy frames: four facing right, then four facing left.")
        emit(f, "MARIA", "u8", [128], list(memory[MARIA_SPRITE:MARIA_SPRITE + 128]),
             "Maria, who waits in the master bedroom.")
        emit(f, "GUARDIANS", "u8", [2048],
             list(memory[GUARDIAN_GRAPHICS:GUARDIAN_GRAPHICS + 2048]),
             "Guardian graphics: 64 sprites of 32 bytes.")
        emit(f, "TOILET", "u8", [256], list(memory[TOILET_GRAPHICS:TOILET_GRAPHICS + 256]),
             "The toilet, and Willy being sick into it.")

    with open(os.path.join(OUT, "lib.rs"), "w") as f:
        f.write("""\
//! Jet Set Willy's byte tables, generated from the published disassembly.
//!
//! Nothing here is hand written; see `tools/gen_jsw_data.py`. The tables are the
//! game's own bytes, read out of the image the disassembly assembles to, so
//! they can be checked against it line by line.
//!
//! Jet Set Willy is Copyright (c) 1984 Software Projects Ltd.

pub mod entities;
pub mod items;
pub mod rooms;
pub mod sprites;

/// Rooms in the mansion.
pub const ROOM_COUNT: usize = 64;

/// Bytes in a room definition.
pub const ROOM_SIZE: usize = 256;

/// Items Willy has to collect.
pub const ITEM_COUNT: usize = 83;
""")

    print(f"wrote {OUT}/rooms.rs, entities.rs, items.rs, sprites.rs, lib.rs")


def check(memory):
    """Fail loudly if the image does not look like Jet Set Willy."""
    name = bytes(memory[ROOMS + 0x80: ROOMS + 0xA0]).decode("latin-1").strip()
    if name != "The Off Licence":
        sys.exit(f"room 0 is named {name!r}, expected 'The Off Licence'")

    if memory[ROOMS + 0xE9] != 1:
        sys.exit("room 0's left exit is not room 1; the offsets are wrong")


if __name__ == "__main__":
    main()
