#!/usr/bin/env python3
"""Generate the jsw2-data module from a Jet Set Willy II snapshot.

Not part of the build. Run it only when the tables need to change:

    JSW2_SNAPSHOT=z80/Jet_Set_Willy_II_The_Final_Frontier_1985_Software_Projects.z80 \\
      python3 tools/gen_jsw2_data.py crates/jsw2-data/src

There is no published disassembly of Jet Set Willy II, so the source is the
game's own memory rather than an assembled disassembly. What is emitted is the
half of the address space the game keeps its data in, exactly as it sits there,
plus the addresses that lead into it. The engine then walks it as the original
does; nothing here decodes anything, so no original routine ends up in Python.

The format is documented at https://www.seasip.info/Jsw/jsw2room.html
"""

import os
import sys

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from jsw_snapshot import load_z80, word

SNAPSHOT = os.environ.get(
    "JSW2_SNAPSHOT",
    "z80/Jet_Set_Willy_II_The_Final_Frontier_1985_Software_Projects.z80",
)
OUT = sys.argv[1] if len(sys.argv) > 1 else "crates/jsw2-data/src"

# The window emitted: everything the rooms need lives in the top half.
BASE = 0x8000
LENGTH = 0x10000 - BASE

# The room table is found through this word rather than hardcoded, as the
# format notes advise, because it moves if the room count changes.
ROOM_TABLE_POINTER = 0x7E69
# Cell graphics: nine bytes each, an attribute and eight pixel rows, indexed by
# a 9-bit value times nine.
CELL_TABLE = 0x8C78
# The words room names are built from, each ending in a byte with bit 7 set.
TOKENS = 0xFA85
ROOM_COUNT = 134

HEAD = """\
// Generated by tools/gen_jsw2_data.py from a Jet Set Willy II snapshot.
// Jet Set Willy II is Copyright (c) 1985 Software Projects Ltd.
// Do not edit by hand.

"""


def check(memory):
    """Fail loudly unless this really is Jet Set Willy II and the tables resolve."""
    signature = bytes(memory[0x6480:0x6493]).decode("latin-1")
    if signature != "THE FINAL FROINTIER":
        sys.exit(f"this snapshot says {signature!r}, which is not Jet Set Willy II")

    table = word(memory, ROOM_TABLE_POINTER)
    if not BASE <= table < 0xFFFF:
        sys.exit(f"the room table is at {table:#06x}, outside the emitted window")

    for number in range(ROOM_COUNT):
        entry = word(memory, table + 2 * number)
        if not BASE <= entry < 0xFFFF:
            sys.exit(f"room {number} is at {entry:#06x}, outside the emitted window")

        shape = word(memory, entry)
        if not BASE <= shape < 0xFFFF:
            sys.exit(f"room {number} has its shape at {shape:#06x}")

        # The shape decompresses to 512 cells. A byte below 144 is a cell type
        # in bits 4 to 7 and a repeat count less one in bits 0 to 3; anything
        # higher is that many air cells less 127. The last run is allowed to
        # overshoot - nine rooms do - so this counts up to 512 and stops.
        cells, at = 0, shape
        while cells < 512:
            byte = memory[at]
            at += 1
            cells += (byte & 15) + 1 if byte < 144 else byte - 127
            if at > shape + 512:
                sys.exit(f"room {number}'s shape does not end")

        # The name follows eight pattern bytes, HBITS and the name/border byte.
        # Its last character has bit 7 set.
        at = entry + 12
        for _ in range(40):
            if memory[at] & 128:
                break
            at += 1
        else:
            sys.exit(f"room {number}'s name does not end")

    print(f"  room table at {table:#06x}, {ROOM_COUNT} rooms, all resolving")


def fmt(data):
    """Format bytes as a Rust array body, wrapped at 92 columns."""
    lines, current = [], "    "
    for text in (str(v) + "," for v in data):
        if len(current) + len(text) > 92:
            lines.append(current.rstrip())
            current = "    "
        current += text + " "
    lines.append(current.rstrip())
    return "\n".join(lines)


def main():
    if not os.path.exists(SNAPSHOT):
        sys.exit(
            f"cannot find {SNAPSHOT}\n"
            "put a Jet Set Willy II snapshot in z80/, or set JSW2_SNAPSHOT"
        )

    memory = load_z80(SNAPSHOT)
    check(memory)

    os.makedirs(OUT, exist_ok=True)
    with open(os.path.join(OUT, "lib.rs"), "w") as f:
        f.write(HEAD)
        f.write("""\
//! Jet Set Willy II's data, as the bytes the game itself holds.
//!
//! There is no disassembly of this game to read, so what is here is the top
//! half of its address space, lifted out of a snapshot. The engine walks it by
//! absolute address exactly as the original does, which is why the addresses
//! below are the game's own rather than offsets into an array.
//!
//! Jet Set Willy II is Copyright (c) 1985 Software Projects Ltd.

/// Where [`IMAGE`] starts in the machine's address space.
pub const BASE: u16 = {base};

/// Rooms in the mansion.
pub const ROOM_COUNT: usize = {rooms};

/// The word here holds the address of the room table. The format notes say to
/// read it rather than hardcode the table, because it moves if the room count
/// changes - so the engine reads it, and this is the only fixed address.
pub const ROOM_TABLE_POINTER: u16 = {pointer};

/// Cell graphics: nine bytes each, an attribute and eight pixel rows.
pub const CELL_TABLE: u16 = {cells};

/// The words room names are built from, each ending in a byte with bit 7 set.
pub const TOKENS: u16 = {tokens};

/// The byte at `addr`, or zero below [`BASE`].
#[must_use]
pub fn read(addr: u16) -> u8 {{
    match addr.checked_sub(BASE) {{
        Some(offset) => IMAGE[offset as usize],
        None => 0,
    }}
}}

/// The little-endian word at `addr`.
#[must_use]
pub fn word(addr: u16) -> u16 {{
    u16::from(read(addr)) | (u16::from(read(addr.wrapping_add(1))) << 8)
}}

/// The top half of the address space, as the game leaves it.
///
/// A static rather than a const: it is 32K, and a const that size is copied in
/// at every use.
pub static IMAGE: [u8; {length}] = [
{image}
];
""".format(
            base=BASE,
            rooms=ROOM_COUNT,
            pointer=ROOM_TABLE_POINTER,
            cells=CELL_TABLE,
            tokens=TOKENS,
            length=LENGTH,
            image=fmt(memory[BASE:BASE + LENGTH]),
        ))

    print(f"wrote {OUT}/lib.rs")


main()
