#!/usr/bin/env python3
"""Generate the jsw-data modules from SkoolKit's Jet Set Willy disassembly.

Not part of the build. Run it only when the tables need to change:

    uv tool install skoolkit          # provides skool2bin.py
    git clone --depth 1 \\
      https://gitlab.com/z80-source-code-software/other-systems/jet-set-willy-disassembly---zx-spectrum \\
      /tmp/jsw
    python3 tools/gen_jsw_data.py crates/jsw-data/src

Setting JSW_SNAPSHOT to a .z80 of the game additionally checks the bytes against
a real dump. The snapshot is a check rather than a source, and is not committed.

SkoolKit assembles the .skool file back into the 64K image the game ran in, and
everything below is read out of that by absolute address. So what lands in
jsw-data is the game's own bytes rather than anyone's transcription of them, and
it can be checked against the disassembly line by line.
"""

import os
import re
import subprocess
import sys
import tempfile

sys.path.insert(0, os.path.dirname(os.path.abspath(__file__)))
from jsw_snapshot import load_z80

SKOOL = os.environ.get("JSW_SKOOL", "/tmp/jsw/sources/jsw.skool")
OUT = sys.argv[1] if len(sys.argv) > 1 else "crates/jsw-data/src"

# Where the game keeps things. Confirmed against the disassembly.
ROOMS = 0xC000
ROOM_COUNT = 64
ROOM_SIZE = 0x100

ENTITY_DEFS = 0xA000
# The original computes an entity definition's address as 40960 + 8 * N with no
# check on N, and a few rooms name an N past the 128 definitions that exist. So
# the window emitted here is the full 256 the arithmetic can reach, overlapping
# the item table just as the machine's memory does.
ENTITY_DEF_COUNT = 256
ENTITY_DEF_SIZE = 8

ITEM_TABLE = 0xA400
FIRST_ITEM = 173

WILLY_SPRITES = 0x9D00
MARIA_SPRITE = 0x9C80
# The foot and the barrel of the game over sequence, which are also guardians
# in The Nightmare Room, Ballroom East and Top Landing.
FOOT_SPRITE = 0x9C40
BARREL_SPRITE = 0x9C60
# Guardians name a page in the sixth byte of their buffer and the game reads
# that page of memory, wherever it is. Most of them point into the block from
# 0xAB00 up to the room definitions, but nine of them - Ballroom East's barrel,
# Top Landing's, and every one in The Nightmare Room - are on page 0x9C, which
# is where the foot, the barrel and Maria live. So the window has to start
# there, and it takes in Willy's sprites, the entity definitions and the item
# table on the way past, exactly as the machine's memory does.
GUARDIAN_GRAPHICS = 0x9C00
GUARDIAN_GRAPHICS_LEN = ROOMS - GUARDIAN_GRAPHICS
TOILET_GRAPHICS = 0xA600
ROPE_TABLE = 0x8300
SCREEN_TABLE = 0x8200
# Moonlight Sonata for the title screen, terminated by 255, and If I Were a
# Rich Man for the game itself, which runs round and round.
THEME_TUNE = 0x85FB
THEME_TUNE_LEN = 100
GAME_TUNE = 0x865F
GAME_TUNE_LEN = 64
HUD_ATTRS = 39424

# The title screen: the picture is made of attributes and one of four triangle
# characters per cell, not of a bitmap. See the routine at 34762.
TITLE_ATTRS = 38912
TRIANGLES = 33841
INTRO_MESSAGE = 33876
INTRO_MESSAGE_LEN = 256

HEAD = """\
// Generated by tools/gen_jsw_data.py from the published Jet Set Willy disassembly.
// Jet Set Willy is Copyright (c) 1984 Software Projects Ltd.
// Do not edit by hand.

"""


# ---- reading the disassembly ------------------------------------------------

def load_image(path):
    """Assemble the .skool file into a 64K image.

    SkoolKit's own assembler does this. Walking the DEFB lines by hand almost
    works, but a few hundred bytes of rooms 47 and 61 to 63 are disassembled as
    instructions rather than data — those rooms hold code and unused junk in the
    real game — and reassembling those needs a Z80 assembler.
    """
    with tempfile.TemporaryDirectory() as work:
        binary = os.path.join(work, "jsw.bin")
        result = subprocess.run(
            ["skool2bin.py", "--data", path, binary],
            capture_output=True, text=True,
        )
        if result.returncode != 0:
            sys.exit(f"skool2bin.py failed:\n{result.stderr.strip()}")

        # It reports the address range it wrote; the file itself is just bytes.
        match = re.search(r"start=(\d+)", result.stderr + result.stdout)
        if not match:
            sys.exit(f"could not read skool2bin's output:\n{result.stderr.strip()}")
        base = int(match.group(1))

        with open(binary, "rb") as handle:
            data = handle.read()

    memory = bytearray(65536)
    memory[base:base + len(data)] = data
    return memory


def verify(memory, snapshot_path):
    """Check the disassembly's image against a real snapshot of the game."""
    snapshot = load_z80(snapshot_path)
    # The item table's collection flag is live state: a snapshot taken after the
    # game has started has it set the other way for each of the 83 items. Only
    # that bit may differ, so it is masked out rather than ignored.
    collected = 64
    regions = [
        ("rooms", ROOMS, ROOM_COUNT * ROOM_SIZE, 255),
        # Only the 128 real definitions; the window emitted is wider than that
        # and runs into the item table, whose flags are live state.
        ("entity definitions", ENTITY_DEFS, 128 * ENTITY_DEF_SIZE, 255),
        ("item table", ITEM_TABLE, 512, 255 - collected),
        ("Willy's sprites", WILLY_SPRITES, 256, 255),
        # The guardian window spans the item table on its way up, and those
        # flags are live state, so it is checked either side of it instead.
        ("guardian graphics", GUARDIAN_GRAPHICS, ITEM_TABLE - GUARDIAN_GRAPHICS, 255),
        ("guardian graphics (2)", ITEM_TABLE + 512, ROOMS - ITEM_TABLE - 512, 255),
    ]
    bad = 0
    for name, start, length, mask in regions:
        differing = sum(
            1
            for i in range(length)
            if memory[start + i] & mask != snapshot[start + i] & mask
        )
        status = "matches" if differing == 0 else f"DIFFERS in {differing} bytes"
        print(f"  {name:20} {status}")
        bad += differing
    if bad:
        sys.exit(f"{bad} bytes differ from {snapshot_path}")
    print("the disassembly and the snapshot agree")


# ---- writing Rust -----------------------------------------------------------

def fmt(data):
    """Format a nested list as a Rust array literal, wrapped at 92 columns."""
    if isinstance(data[0], list):
        return "[\n" + ",\n".join("    " + fmt_row(row) for row in data) + "\n]"
    return fmt_row(data)


def fmt_row(row):
    if isinstance(row[0], list):
        return "[" + ", ".join(fmt_row(inner) for inner in row) + "]"
    body = ", ".join(str(v) for v in row)
    if len(body) <= 88:
        return "[" + body + "]"
    lines, current = [], "    "
    for value_text in (str(v) + "," for v in row):
        if len(current) + len(value_text) > 92:
            lines.append(current.rstrip())
            current = "    "
        current += value_text + " "
    lines.append(current.rstrip().rstrip(","))
    return "[\n" + "\n".join("    " + line for line in lines) + "\n    ]"


def emit(handle, name, rust_ty, dims, data, doc):
    ty = rust_ty
    for dim in reversed(dims):
        ty = f"[{ty}; {dim}]"
    handle.write(f"/// {doc}\n")
    handle.write(f"pub const {name}: {ty} = {fmt(data)};\n\n")


# ---- extraction -------------------------------------------------------------

def main():
    if not os.path.exists(SKOOL):
        sys.exit(
            f"cannot find {SKOOL}\n"
            "clone the disassembly first, or set JSW_SKOOL to its jsw.skool"
        )

    memory = load_image(SKOOL)
    check(memory)

    # Optional: prove the disassembly assembles to the same bytes a real
    # snapshot holds. The snapshot is never committed and is not needed to
    # generate; this is a check, not a source.
    snapshot = os.environ.get("JSW_SNAPSHOT")
    if snapshot:
        verify(memory, snapshot)

    os.makedirs(OUT, exist_ok=True)
    rooms = [
        memory[ROOMS + n * ROOM_SIZE: ROOMS + (n + 1) * ROOM_SIZE]
        for n in range(ROOM_COUNT)
    ]

    with open(os.path.join(OUT, "rooms.rs"), "w") as f:
        f.write(HEAD)
        emit(f, "ROOMS", "u8", [ROOM_COUNT, ROOM_SIZE], [list(r) for r in rooms],
             "The 64 room definitions, 256 bytes each, exactly as they sit at 49152.")
        emit(f, "ROOM_NAMES", "u8", [ROOM_COUNT, 32],
             [list(r[0x80:0xA0]) for r in rooms],
             "Room names, 32 bytes each, printed through the ROM font. Rooms 61 to "
             "63 hold code rather than a room, so their names are not text.")

    with open(os.path.join(OUT, "entities.rs"), "w") as f:
        f.write(HEAD)
        defs = [
            list(memory[ENTITY_DEFS + n * ENTITY_DEF_SIZE:
                        ENTITY_DEFS + (n + 1) * ENTITY_DEF_SIZE])
            for n in range(ENTITY_DEF_COUNT)
        ]
        emit(f, "ENTITY_DEFS", "u8", [ENTITY_DEF_COUNT, ENTITY_DEF_SIZE], defs,
             "Entity definitions: ropes, arrows and guardians, eight bytes each. "
             "Only the first 128 are definitions; the rest is whatever the "
             "original would read past them, which a few rooms do.")
        emit(f, "ROPE_TABLE", "u8", [256], list(memory[ROPE_TABLE:ROPE_TABLE + 256]),
             "How far to rotate a rope's sprite at each point along its swing.")
        emit(f, "SCREEN_TABLE", "u8", [256],
             list(memory[SCREEN_TABLE:SCREEN_TABLE + 256]),
             "Screen-buffer address of each guardian y-coordinate, as low and "
             "high byte pairs indexed by the y-coordinate itself.")

    with open(os.path.join(OUT, "hud.rs"), "w") as f:
        f.write(HEAD)
        emit(f, "ATTRS", "u8", [256], list(memory[HUD_ATTRS:HUD_ATTRS + 256]),
             "Attributes for the bottom third of the screen, where the room "
             "name, the item count, the clock and the lives are shown.")

    with open(os.path.join(OUT, "title.rs"), "w") as f:
        f.write(HEAD)
        emit(f, "ATTRS", "u8", [512], list(memory[TITLE_ATTRS:TITLE_ATTRS + 512]),
             "Attributes for the top two thirds of the title screen. The "
             "picture is drawn from these: every cell whose attribute is not "
             "one of the five flat values gets a triangle in it.")
        emit(f, "TRIANGLES", "u8", [4, 8],
             [list(memory[TRIANGLES + n * 8: TRIANGLES + (n + 1) * 8]) for n in range(4)],
             "The four triangle characters the title picture is built from.")
        message = bytes(memory[INTRO_MESSAGE:INTRO_MESSAGE + INTRO_MESSAGE_LEN])
        # 127 is the copyright sign in the Spectrum's character set.
        text = message.decode("latin-1").replace("\x7f", "\u00a9")
        f.write("/// The message that scrolls across the title screen, which the "
                "original prints\n/// thirty-two characters at a time.\n")
        f.write(f"pub const INTRO_MESSAGE: &str = {text!r};\n\n".replace("'", '"'))

    with open(os.path.join(OUT, "music.rs"), "w") as f:
        f.write(HEAD)
        emit(f, "THEME", "u8", [THEME_TUNE_LEN],
             list(memory[THEME_TUNE:THEME_TUNE + THEME_TUNE_LEN]),
             "Moonlight Sonata, played over the title screen. Each byte is a "
             "pitch delay, and 255 ends it.")
        emit(f, "GAME", "u8", [GAME_TUNE_LEN],
             list(memory[GAME_TUNE:GAME_TUNE + GAME_TUNE_LEN]),
             "If I Were a Rich Man, played while the game runs. Each byte is a "
             "pitch delay, and the tune repeats for ever.")

    with open(os.path.join(OUT, "items.rs"), "w") as f:
        f.write(HEAD)
        f.write("/// The lowest numbered item. Items below this are not in the game.\n")
        f.write(f"pub const FIRST_ITEM: usize = {FIRST_ITEM};\n\n")
        emit(f, "ITEM_TABLE", "u8", [2, 256],
             [list(memory[ITEM_TABLE:ITEM_TABLE + 256]),
              list(memory[ITEM_TABLE + 256:ITEM_TABLE + 512])],
             "The two halves of the item table: room and position of each of the 83 items.")

    with open(os.path.join(OUT, "sprites.rs"), "w") as f:
        f.write(HEAD)
        emit(f, "WILLY", "u8", [256], list(memory[WILLY_SPRITES:WILLY_SPRITES + 256]),
             "Eight 16x16 Willy frames: four facing right, then four facing left.")
        emit(f, "MARIA", "u8", [128], list(memory[MARIA_SPRITE:MARIA_SPRITE + 128]),
             "Maria, who waits in the master bedroom.")
        emit(f, "FOOT", "u8", [32], list(memory[FOOT_SPRITE:FOOT_SPRITE + 32]),
             "The foot that comes down on the barrel when the game is over.")
        emit(f, "BARREL", "u8", [32], list(memory[BARREL_SPRITE:BARREL_SPRITE + 32]),
             "The barrel Willy stands on while the game is over.")
        emit(f, "GUARDIANS", "u8", [GUARDIAN_GRAPHICS_LEN],
             list(memory[GUARDIAN_GRAPHICS:GUARDIAN_GRAPHICS + GUARDIAN_GRAPHICS_LEN]),
             "Guardian graphics, from 39936 up to the room definitions. A "
             "guardian names its page in the sixth byte of its buffer, and "
             "those pages run from 156 - the foot, the barrel and Maria - all "
             "the way to 49152, so the window takes in Willy's sprites, the "
             "entity definitions and the item table on the way past.")
        emit(f, "TOILET", "u8", [256], list(memory[TOILET_GRAPHICS:TOILET_GRAPHICS + 256]),
             "The toilet, and Willy being sick into it.")

    with open(os.path.join(OUT, "lib.rs"), "w") as f:
        f.write("""\
//! Jet Set Willy's byte tables, generated from the published disassembly.
//!
//! Nothing here is hand written; see `tools/gen_jsw_data.py`. The tables are the
//! game's own bytes, read out of the image the disassembly assembles to, so
//! they can be checked against it line by line.
//!
//! Jet Set Willy is Copyright (c) 1984 Software Projects Ltd.

pub mod entities;
pub mod hud;
pub mod items;
pub mod music;
pub mod rooms;
pub mod sprites;
pub mod title;

/// Rooms in the mansion.
pub const ROOM_COUNT: usize = 64;

/// Bytes in a room definition.
pub const ROOM_SIZE: usize = 256;

/// Items Willy has to collect.
pub const ITEM_COUNT: usize = 83;
""")

    print(
        f"wrote {OUT}/rooms.rs, entities.rs, items.rs, sprites.rs, music.rs, "
        f"hud.rs, title.rs, lib.rs"
    )


def check(memory):
    """Fail loudly if the image does not look like Jet Set Willy."""
    name = bytes(memory[ROOMS + 0x80: ROOMS + 0xA0]).decode("latin-1").strip()
    if name != "The Off Licence":
        sys.exit(f"room 0 is named {name!r}, expected 'The Off Licence'")

    if memory[ROOMS + 0xE9] != 1:
        sys.exit("room 0's left exit is not room 1; the offsets are wrong")


if __name__ == "__main__":
    main()
